'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true,
});
exports.FORWARD_SLASH =
  exports.DECIMAL_POINT =
  exports.DASH =
  exports.COMMA =
  exports.F12 =
  exports.F11 =
  exports.F10 =
  exports.F9 =
  exports.F8 =
  exports.F7 =
  exports.F6 =
  exports.F5 =
  exports.F4 =
  exports.F3 =
  exports.F2 =
  exports.F1 =
  exports.A =
  exports.C =
  exports.WINDOWS =
  exports.UP =
  exports.TAB =
  exports.SPACE =
  exports.SHIFT =
  exports.RIGHT =
  exports.PAGE_UP =
  exports.PAGE_DOWN =
  exports.NUMPAD_SUBTRACT =
  exports.NUMPAD_MULTIPLY =
  exports.NUMPAD_ENTER =
  exports.NUMPAD_DIVIDE =
  exports.NUMPAD_DECIMAL =
  exports.NUMPAD_ADD =
  exports.MENU =
  exports.LEFT =
  exports.INSERT =
  exports.HOME =
  exports.ESCAPE =
  exports.ENTER =
  exports.END =
  exports.DOWN =
  exports.DELETE =
  exports.CONTROL =
  exports.COMMAND_RIGHT =
  exports.COMMAND_LEFT =
  exports.COMMAND =
  exports.CAPS_LOCK =
  exports.BACKSPACE =
  exports.ALT =
    void 0;
exports.ALT = 18;
exports.BACKSPACE = 8;
exports.CAPS_LOCK = 20;
exports.COMMAND = 91;
exports.COMMAND_LEFT = 91;
exports.COMMAND_RIGHT = 93;
exports.CONTROL = 17;
exports.DELETE = 46;
exports.DOWN = 40;
exports.END = 35;
exports.ENTER = 13;
exports.ESCAPE = 27;
exports.HOME = 36;
exports.INSERT = 45;
exports.LEFT = 37;
exports.MENU = 93;
exports.NUMPAD_ADD = 107;
exports.NUMPAD_DECIMAL = 110;
exports.NUMPAD_DIVIDE = 111;
exports.NUMPAD_ENTER = 108;
exports.NUMPAD_MULTIPLY = 106;
exports.NUMPAD_SUBTRACT = 109;
exports.PAGE_DOWN = 34;
exports.PAGE_UP = 33;
exports.RIGHT = 39;
exports.SHIFT = 16;
exports.SPACE = 32;
exports.TAB = 9;
exports.UP = 38;
exports.WINDOWS = 91;
exports.C = 67;
exports.A = 65;
exports.F1 = 112;
exports.F2 = 113;
exports.F3 = 114;
exports.F4 = 115;
exports.F5 = 116;
exports.F6 = 117;
exports.F7 = 118;
exports.F8 = 119;
exports.F9 = 120;
exports.F10 = 121;
exports.F11 = 122;
exports.F12 = 123;
exports.COMMA = 188;
exports.DASH = 189;
exports.DECIMAL_POINT = 190;
exports.FORWARD_SLASH = 191;
